version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.dagger:dagger
    versions:
    - 2.31.2
    - "2.32"
    - "2.33"
    - "2.34"
    - 2.34.1
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: androidx.lifecycle:lifecycle-reactivestreams-ktx
    versions:
    - 2.3.0
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
